In [2]:
import pandas as pd
import os
os.chdir(r"C:\Users\Gyu\Desktop\mywork\FastOnline\2. 탐색적 데이터 분석\데이터")
df = pd.read_csv("Telco_customer_info.csv")
df.set_index('customerID', inplace = True)
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
customerID,,,,,,,,,,,,,,,,,,,
7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

In [3]:
df = pd.get_dummies(df, drop_first = True)
df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
customerID,,,,,,,,,,,,,,,,,,,,,
7590-VHVEG,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
5575-GNVDE,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
3668-QPYBK,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
7795-CFOCW,0,45,42.30,1840.75,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
9237-HQITU,0,2,70.70,151.65,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0

In [4]:
from sklearn.cluster import AgglomerativeClustering
clusters = AgglomerativeClustering(n_clusters = 3,
                                   affinity = 'euclidean',
                                   linkage = 'ward').fit(df)

In [5]:
df['군집정보'] = clusters.labels_
df['군집정보'].head()

customerID
7590-VHVEG    2
5575-GNVDE    1
3668-QPYBK    2
7795-CFOCW    1
9237-HQITU    2
Name: 군집정보, dtype: int64

In [6]:
df.groupby(['군집정보'])[['MonthlyCharges', 'TotalCharges','SeniorCitizen', 'StreamingTV_Yes']].mean()

      MonthlyCharges  TotalCharges  SeniorCitizen  StreamingTV_Yes
군집정보
0          92.846384   5615.733243       0.213708         0.744738
1          65.558747   2192.519269       0.181723         0.390078
2          48.428814    444.712194       0.121936         0.176471

### 구매 기록 기준 고객 군집화

In [7]:
df = pd.read_csv("베스트셀러_도서구매기록.txt", sep = "\t", engine = "python")

In [8]:
matrix_df = pd.crosstab(index = df['회원번호'], columns = df['책제목'])
matrix_df.head()

책제목,1cm+,21세기 자본,EBS FM 라디오 고교 영어듣기 (2014년),EBS N제 국어영역 국어 270제 A형 (2014년),EBS N제 국어영역 국어 270제 B형 (2014년),EBS N제 영어영역 영어 280제 (2014년),EBS 수능완성 국어영역 국어 A형 유형편+실전편 (2014년),EBS 수능완성 국어영역 국어 B형 유형편+실전편 (2014년),EBS 수능완성 수학영역 기하와 벡터 (2014년),EBS 수능완성 수학영역 미적분과 통계 기본 유형편+실전편 A형 (2014년),...,정글만리 3,제3인류 3,창문 넘어 도망친 100세 노인,책은 도끼다,"총, 균, 쇠",칼 비테의 자녀교육 불변의 법칙,코스모스,해커스 토익 Listening,해커스 토익 Reading,해커스 토익 보카 Vocabulary
회원번호,,,,,,,,,,,,,,,,,,,,,
808,0,0,1,0,1,1,0,3,0,1,...,0,0,1,0,0,0,0,0,0,0
1101,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1479,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1805,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2011,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

- 0이 많은 희소 행렬이라 jaccard 사용
- jaccard에서는 1이상이면 1로 취급

In [10]:
from sklearn.cluster import AgglomerativeClustering as AC
clustering_model = AC(n_clusters = 10,
                      affinity = "jaccard",
                      linkage = "average")
clustering_model.fit(matrix_df)

cluster_labels = clustering_model.labels_

# 회원별 소속 군집 확인
cluster_info = pd.DataFrame({"회원ID":matrix_df.index, "소속군집":cluster_labels})
cluster_info.head()

   회원ID  소속군집
0   808     0
1  1101     0
2  1479     0
3  1805     0
4  2011     0

In [11]:
cluster_info['소속군집'].value_counts() # 대다수가 0번 군집에 속함

0    665
1     12
2      6
3      4
8      2
4      2
9      1
7      1
6      1
5      1
Name: 소속군집, dtype: int64

In [12]:
matrix_df_with_cluster_info = pd.merge(matrix_df, cluster_info, left_index = True, right_on = '회원ID')
matrix_df_with_cluster_info.head()

,1cm+,21세기 자본,EBS FM 라디오 고교 영어듣기 (2014년),EBS N제 국어영역 국어 270제 A형 (2014년),EBS N제 국어영역 국어 270제 B형 (2014년),EBS N제 영어영역 영어 280제 (2014년),EBS 수능완성 국어영역 국어 A형 유형편+실전편 (2014년),EBS 수능완성 국어영역 국어 B형 유형편+실전편 (2014년),EBS 수능완성 수학영역 기하와 벡터 (2014년),EBS 수능완성 수학영역 미적분과 통계 기본 유형편+실전편 A형 (2014년),...,창문 넘어 도망친 100세 노인,책은 도끼다,"총, 균, 쇠",칼 비테의 자녀교육 불변의 법칙,코스모스,해커스 토익 Listening,해커스 토익 Reading,해커스 토익 보카 Vocabulary,회원ID,소속군집
0,0,0,1,0,1,1,0,3,0,1,...,1,0,0,0,0,0,0,0,808,0
1,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1101,0
2,0,0,1,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1479,0
3,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1805,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2011,0

In [13]:
matrix_df_with_cluster_info.groupby(['소속군집'])[matrix_df.columns].mean()

,1cm+,21세기 자본,EBS FM 라디오 고교 영어듣기 (2014년),EBS N제 국어영역 국어 270제 A형 (2014년),EBS N제 국어영역 국어 270제 B형 (2014년),EBS N제 영어영역 영어 280제 (2014년),EBS 수능완성 국어영역 국어 A형 유형편+실전편 (2014년),EBS 수능완성 국어영역 국어 B형 유형편+실전편 (2014년),EBS 수능완성 수학영역 기하와 벡터 (2014년),EBS 수능완성 수학영역 미적분과 통계 기본 유형편+실전편 A형 (2014년),...,정글만리 3,제3인류 3,창문 넘어 도망친 100세 노인,책은 도끼다,"총, 균, 쇠",칼 비테의 자녀교육 불변의 법칙,코스모스,해커스 토익 Listening,해커스 토익 Reading,해커스 토익 보카 Vocabulary
소속군집,,,,,,,,,,,,,,,,,,,,,
0,0.063158,0.039098,0.440602,0.264662,0.354887,0.619549,0.312782,0.372932,0.288722,0.324812,...,0.099248,0.033083,0.156391,0.042105,0.097744,0.034586,0.010526,0.03609,0.039098,0.04812
1,0.500000,0.500000,0.000000,0.000000,0.000000,0.083333,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.333333,1.166667,0.500000,0.000000,0.000000,0.000000,0.00000,0.000000,0.25000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,1.000000,0.500000,0.000000,0.00000,0.000000,0.00000
3,0.000000,0.000000,0.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
4,0.000000,0.000000,2.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000

In [14]:
# 군집별로 가장 많이 구매하는 책 목록 확인
matrix_df_with_cluster_info.groupby(['소속군집'])[matrix_df.columns].mean().idxmax(axis = 1)

소속군집
0    EBS 수능특강 영어영역 영어 (2014년)
1           창문 넘어 도망친 100세 노인
2                 나미야 잡화점의 기적
3              어떻게 원하는 것을 얻는가
4    EBS 수능특강 영어영역 영어 (2014년)
5                   강신주의 감정수업
6                    마법천자문 27
7                 꾸뻬 씨의 행복 여행
8              나는 까칠하게 살기로 했다
9                    월급쟁이 부자들
dtype: object

### K-means

In [16]:
df = pd.read_csv("Telco_customer_info.csv")
df.set_index('customerID', inplace = True)
df = pd.get_dummies(df, drop_first = True)
df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
customerID,,,,,,,,,,,,,,,,,,,,,
7590-VHVEG,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
5575-GNVDE,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
3668-QPYBK,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
7795-CFOCW,0,45,42.30,1840.75,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
9237-HQITU,0,2,70.70,151.65,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0

In [17]:
from sklearn.cluster import KMeans
clusters = KMeans(n_clusters = 3).fit(df)

In [18]:
# 군집 중심 확인 및 이름 붙이기
pd.DataFrame(clusters.cluster_centers_,
             columns = df.columns,
             index = range(3))

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0.216733,64.384861,97.979243,6297.778685,0.499602,0.740239,0.336255,0.998406,0.001594,0.829482,...,-4.163336e-16,0.807171,-4.163336e-16,0.817530,0.301195,0.517131,0.710757,0.332271,0.288446,0.051793
1,0.128661,18.264522,49.767331,688.070319,0.501200,0.376140,0.285166,0.891263,0.108737,0.269803,...,3.643783e-01,0.194911,3.643783e-01,0.195391,0.145943,0.165627,0.526644,0.164186,0.346375,0.324532
2,0.207325,44.132216,77.818963,3281.164184,0.517691,0.556797,0.303538,0.860335,0.139665,0.497827,...,1.241465e-03,0.545003,1.241465e-03,0.553073,0.301676,0.214773,0.671633,0.260708,0.347610,0.116077